### ISSUE TITLE
Would like for the gophers to have long-haired options. 

### ISSUE THREAD

**Issue by si74** [matryer/gopherize.me#1]
For many individuals, this limits our gopher accessorizing choices. Note that this does not quite resemble me: 
<img width="656" alt="screen shot 2017-01-25 at 4 52 44 pm" src="https://cloud.githubusercontent.com/assets/913035/22310904/ea115dd0-e31e-11e6-8c54-90015bd4c78e.png">

**Comment by dgryski** [comment]
There are now many more hair styles available.

**Comment by mongrelion** [comment]
Any chances of adding a dreadlocks and afro options? :)

**Comment by matryer** [comment]
For artwork requests, please tweet https://twitter.com/ashleymcnamara
