### ISSUE TITLE
404 for most ui elements at gopherize.me

### ISSUE THREAD

**Issue by kamilsk** [matryer/gopherize.me#4]
Hi! As example:

https://storage.googleapis.com/gopherizeme.appspot.com/artwork/026-Facial_Hair/amazing_beard.png - 404

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by kamilsk** [comment]
hm, sorry, now problem is gone

**Comment by matryer** [comment]
Artwork is in flux still - once it settles down, these issues will go away.
