### ISSUE TITLE
Some options not rendering

### ISSUE THREAD

**Issue by mjbrender** [matryer/gopherize.me#6]
First off, this is the most important and awesome GitHub issue I've ever opened. Thank you for marking such a fun site! 

Now, to the issues: 

1. "Goofy Eyes" are not rendering, though it does show up in the sidebar

![eyes-gophering](https://cloud.githubusercontent.com/assets/1744971/22352735/33776920-e3d2-11e6-8fda-99f91c4e410b.gif)

2. The first item in every category is neither showing up nor rendering 

![gophering](https://cloud.githubusercontent.com/assets/1744971/22352738/37631ac0-e3d2-11e6-950c-e30a20647aab.gif)

**Comment by nilslice** [comment]
@mjbrender - regarding your 2nd point, I believe the empty item is to reset that category and clear the Gopher (i.e. take off the King crown without replacing it with another accessory).

**Comment by matryer** [comment]
Thanks for your kind words :)

When the artwork changes, we are in caching limbo for a bit. Try a hard-refresh whenever you see something not working.

**Comment by matryer** [comment]
And @nilslice is right - the empty box is deliberate.
