### ISSUE TITLE
Short Black Beard doesn't fit 'normal' eyes

### ISSUE THREAD

**Issue by hackebrot** [matryer/gopherize.me#8]
Hey!

Thank you @ashleymcnamara & @matryer for creating this project! It's fun 😂 

I noticed that the *normal* eyes don't quite fit with the *Short Black Beard*, see screenshot below.

---

<img width="698" alt="gopher_bug" src="https://cloud.githubusercontent.com/assets/6024445/22566822/6355357e-e985-11e6-838e-70c4ca69e882.png">

**Comment by ashleymcnamara** [comment]
I'll get it resized. 🙌

Ashley McNamara
Developer Evangelist | Rackspace
m:	(650) 533-9961
w:	www.rackspace.com  e: ashleymcnamara1@gmail.com

**Comment by hackebrot** [comment]
Thank you! 👏

**Comment by matryer** [comment]
Best bug report ever.

**Comment by ashleymcnamara** [comment]
Update complete, check in tomorrow and let me know how it works @hackebrot

**Comment by hackebrot** [comment]
Looks like the beard image center doesn't quiet match the eyes? 😢 

---

<img width="400" alt="gopher_bug" src="https://cloud.githubusercontent.com/assets/6024445/22948667/4bbb2d80-f2f7-11e6-8bff-61da33dc7404.png">

**Comment by ashleymcnamara** [comment]
Let me see what's going on. 😩


Ashley McNamara
Developer Evangelist | Rackspace
m:	(650) 533-9961
w:	www.rackspace.com  e: ashleymcnamara1@gmail.com

**Comment by hackebrot** [comment]
@ashleymcnamara Please don't worry too much about it!

**Comment by ashleymcnamara** [comment]
It's no problem 🤗

Ashley McNamara
Developer Evangelist | Rackspace
m:	(650) 533-9961
w:	www.rackspace.com  e: ashleymcnamara1@gmail.com
